# Generated by Django 6.0.1 on 2026-01-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(blank=True, default='Mon-Fri', max_length=100),
        ),
    ]
